### ISSUE TITLE
sm64coopdx fails to compile on macOS Sonoma 14.5 (Apple Silicon)

### ISSUE THREAD

**Issue by supahfox** [coop-deluxe/sm64coopdx#162]
```
Generating endian-bitwidth
Generating:  build/us_pc/sound/sound_data.ctl
Compiling: sound/samples_assets.c -> build/us_pc/sound/samples_assets.o
Compiling: sound/sequences_assets.c -> build/us_pc/sound/sequences_assets.o
sound/sequences_assets.c:4:10: fatal error: 'sound/sequences_offsets.inc.c' file not found
#include "sound/sequences_offsets.inc.c"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [Makefile:1388: build/us_pc/sound/sequences_assets.o] Error 1
```

Also I wanna point out that the [macOS release app ](https://github.com/coop-deluxe/sm64coopdx/releases/download/v1.0/sm64coopdx_v1.0_macOS.zip)isn't opening
<img width="312" alt="Captura de pantalla 2024-07-02 a la(s) 04 45 31" src="https://github.com/coop-deluxe/sm64coopdx/assets/31490939/1c0a1e21-41dc-44b2-a776-bcfcea36bacd">

**Comment by Flower35** [comment]
I was getting the same error both on Windows and on Linux, it was usually at the 2nd attempt on compilation.

My workaround was to enter this in to the shell:
```
$ make build/us_pc/sound/sequences.bin
```
which resolves the issue with `sound/sequences_offsets.inc.c`.

then you can go back to the regular project building process:
```
$ make
```

**Comment by EmeraldLoc** [comment]
After checking out the Mac release, looks like some stuff got changed with permissions, will see why that happened. Enter in your terimnal, head into the app, go contents, macOS, then run chmod +x sm64coopdx. As for the compilation error, never saw that one before, that’s being said, it is known that coopdx fails to compile on Mac rn, will be fixed later, however try what flower35 said above as well.

**Comment by supahfox** [comment]
> After checking out the Mac release, looks like some stuff got changed with permissions, will see why that happened. Enter in your terimnal, head into the app, go contents, macOS, then run chmod +x sm64coopdx. As for the compilation error, never saw that one before, that’s being said, it is known that coopdx fails to compile on Mac rn, will be fixed later, however try what flower35 said above as well.

Now it returns this
```
src/pc/djui/djui_panel_mod_menu.c:56:13: error: expected expression
            struct DjuiButton* button = djui_button_create(parent, hooked->name, DJUI_BUTTON_STYLE_NORMAL, djui_panel_mod_menu_mod_button);
            ^
src/pc/djui/djui_panel_mod_menu.c:57:13: error: use of undeclared identifier 'button'
            button->base.tag = i;
            ^
src/pc/djui/djui_panel_mod_menu.c:60:13: error: expected expression
            struct DjuiCheckbox* checkbox = djui_checkbox_create(parent, hooked->name, &hooked->boolValue, djui_panel_mod_menu_mod_checkbox);
            ^
src/pc/djui/djui_panel_mod_menu.c:61:13: error: use of undeclared identifier 'checkbox'
            checkbox->base.tag = i;
            ^
src/pc/djui/djui_panel_mod_menu.c:64:13: error: expected expression
            struct DjuiSlider* slider = djui_slider_create(parent, hooked->name, &hooked->uintValue, hooked->sliderMin, hooked->sliderMax, djui_panel_mod_menu_mod_slider);
            ^
src/pc/djui/djui_panel_mod_menu.c:65:13: error: use of undeclared identifier 'slider'
            slider->base.tag = i;
            ^
src/pc/djui/djui_panel_mod_menu.c:68:13: error: expected expression
            struct DjuiRect* rect = djui_rect_container_create(parent, 32);
            ^
src/pc/djui/djui_panel_mod_menu.c:70:60: error: use of undeclared identifier 'rect'
                struct DjuiText* text1 = djui_text_create(&rect->base, hooked->name);
                                                           ^
src/pc/djui/djui_panel_mod_menu.c:77:71: error: use of undeclared identifier 'rect'
                struct DjuiInputbox* inputbox = djui_inputbox_create(&rect->base, hooked->length);
                                                                      ^
src/pc/djui/djui_panel_mod_menu.c:87:5: warning: label at end of compound statement is a C2x extension [-Wc2x-extensions]
    }
    ^
src/pc/djui/djui_panel_mod_menu.c:52:69: warning: unused parameter 'parent' [-Wunused-parameter]
static void djui_panel_mod_menu_mod_create_element(struct DjuiBase* parent, int i) {
                                                                    ^
2 warnings and 9 errors generated.
gmake: *** [Makefile:1388: build/us_pc/src/pc/djui/djui_panel_mod_menu.o] Error 1
```

did chmod +x sm64coopdx and executed the script

```
dyld[8358]: Library not loaded: /opt/homebrew/opt/glew/lib/libGLEW.2.2.dylib
  Referenced from: <B53BDAB3-00E5-3F3B-91A9-FC853A82AA0B> /Applications/sm64coopdx.app/Contents/MacOS/sm64coopdx (built for macOS 15.0 which is newer than running OS)
  Reason: tried: '/opt/homebrew/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/opt/homebrew/opt/glew/lib/libGLEW.2.2.dylib' (no such file)
zsh: abort      ./sm64coopdx
```

**Comment by EmeraldLoc** [comment]
Yea, there’s another issue on this, can you download the dmg I sent there and see how that works? For compilation, that’s fixed in the dev branch.

**Comment by supahfox** [comment]
> Yea, there’s another issue on this, can you download the dmg I sent there and see how that works? For compilation, that’s fixed in the dev branch.
If you are talking about the one published 5 hours ago, no, still the same.
I'll try to build from the dev branch and see how it goes

**Comment by supahfox** [comment]
![image](https://github.com/coop-deluxe/sm64coopdx/assets/31490939/4d6fc806-11c6-4ab8-9cce-ba68ee429198)

Also, this happens everytime I open it, so I need to copy the lang folder manually

**Comment by EmeraldLoc** [comment]
Yea I need to update the makefile to do all that properly, since dx seems to actually do directories correctly, unlike what ex-coop did. First need to get the .app in the releases panel.

**Comment by supahfox** [comment]
Yeah mods aren't even working

**Comment by EmeraldLoc** [comment]
Yea, mods, dynos, lang, and palettes folders all need to be moved to the resources folder. Currently working on the makefile rn, will try to get all of this stuff worked out by tonight.

**Comment by AgentXLP** [comment]
Same general issue as #165
Let's continue this there
